import { themePalette } from '../theme/palette';

export const colors = {
	white: themePalette.light.backgroundSecondary,
	screenBackground: themePalette.light.backgroundPrimary,
	brandPrimary: themePalette.light.titlePrimary,
	brandTitle: themePalette.light.titlePrimary,
	brandDark: themePalette.light.titlePrimary,
	textPrimary: themePalette.light.textPrimary,
	textStrong: themePalette.light.textPrimary,
	textSecondary: themePalette.light.textSecondary,
	textMuted: themePalette.light.textTertiary,
	textSubtle: themePalette.light.textTertiary,
	textTertiary: themePalette.light.textTertiary,
	placeholder: themePalette.light.textTertiary,
	termsText: themePalette.light.textPrimary,
	border: '#D2D6E0',
	dotInactive: themePalette.light.systemSecondary,
	surface: themePalette.light.backgroundSecondary,
	surfaceMuted: themePalette.light.buttonTertiary,
	surfaceSoft: themePalette.light.backgroundPrimary,
	surfacePressed: themePalette.light.buttonTertiary,
	bankLogoBackground: themePalette.light.titlePrimary,
	darkModeBackground: themePalette.dark.backgroundPrimary,
	inputBackgroundDark: themePalette.dark.backgroundSecondary,
	buttonDark: themePalette.dark.buttonPrimary,
	actionButtonDark: themePalette.dark.buttonSecondary,
	success: themePalette.light.systemSuccess,
	error: '#DC2626',
} as const;
