export const themePalette = {
	light: {
		textPrimary: '#131313',
		textSecondary: '#6C727F',
		textTertiary: '#8F94A3',
		titlePrimary: '#2C14DD',
		titleSecondary: '#131313',
		backgroundPrimary: '#F5F7FF',
		backgroundSecondary: '#FFFFFF',
		buttonPrimary: '#2C14DD',
		buttonPrimaryContent: '#FFFFFF',
		buttonSecondary: '#FFFFFF',
		buttonSecondaryContent: '#131313',
		buttonTertiary: '#F5F7FF',
		buttonTertiaryContent: '#131313',
		systemSuccess: '#009218',
		systemError: '#DC2626',
		systemPrimary: '#2C14DD',
		systemSecondary: '#B8B8B8',
		borderSubtle: '#D2D6E0',
	},
	dark: {
		textPrimary: '#FFFFFF',
		textSecondary: '#BFB4D5',
		textTertiary: '#ABA2BE',
		titlePrimary: '#F5F7FF',
		titleSecondary: '#FFFFFF',
		backgroundPrimary: '#240F51',
		backgroundSecondary: '#3A2762',
		buttonPrimary: '#E5B4FF',
		buttonPrimaryContent: '#240F51',
		buttonSecondary: '#503F74',
		buttonSecondaryContent: '#FFFFFF',
		buttonTertiary: '#4B3D74',
		buttonTertiaryContent: '#F5F7FF',
		systemSuccess: '#60C771',
		systemError: '#FF5F7F',
		systemPrimary: '#FFFFFF',
		systemSecondary: '#503F74',
		borderSubtle: '#503F74',
	},
} as const;
